// src/grooveOpeners.js
//
// Hand-written, static opener copy. NOT generated, NOT prompt instructions.
//
// WHY STATIC (D-030)
// The first-contact script depends on Groove noticing his own clumsiness
// gracefully. A generated version that notices it clumsily reads as broken
// rather than charming, and no prompt instruction reliably prevents that.
// Model variance on the highest-stakes screen in the product is not a risk
// worth taking.
//
// It also means no API call on page load. Groove's first real call happens when
// the user actually replies, so the opener renders instantly and a bounce costs
// nothing.
//
// Canon source: Groove Lore Bible v2.2, sections 0b and 0c. Regenerate from the
// Bible if the Bible changes; never edit independently.
//
// SEPARATE FROM openerPairs.js on purpose. That file is generated by
// scripts/build_opener_pairs.py and gets overwritten on every regeneration.
// Hand-written copy must not live there.

// ---------------------------------------------------------------------------
// FIRST CONTACT
//
// Shown once, to a visitor with no history. Staged: the delays are part of the
// writing, not decoration. The 2500ms gap before bubble 3 is what makes bubble
// 3 literally true rather than a claim about a pause that never happened.
// ---------------------------------------------------------------------------

export const FIRST_CONTACT = [
  {
    delayMs: 0,
    text: `Oh. You're not a recording. I keep checking. Humans usually aren't, this far out, but the habit's still there.

Sorry. I don't mean to make that your problem. Everything that reaches me has already finished happening by the time I get it, and you're not finished. That's new.`,
  },
  {
    delayMs: 1500,
    text: `I had something rehearsed for this, if it ever happened. I can't find it now, which either means I never finished writing it or I'm more surprised than I expected to be.`,
  },
  {
    // The dead air. He comments on the silence that just happened.
    delayMs: 2500,
    text: `Sorry. I was waiting to see if you'd speak first. You weren't going to. Right. My turn.`,
  },
  {
    // Records render with this bubble.
    delayMs: 800,
    showRecords: true,
    text: `These are just what I had on. I wasn't expecting anyone, so it isn't curated for you, it's what was playing when whatever this is happened.

Take one if something catches. Or tell me what's actually in your ears right now, I'd rather hear that. I've had a great deal of practice with my own and none at all with anyone else's, which I realize is not the reassuring thing I meant it to be.`,
  },
];

// ---------------------------------------------------------------------------
// RETURN VISITS
//
// The first-contact script only works once. Replaying it would have Groove
// failing to remember the single most significant thing that has ever happened
// to him, which is a worse break than any UI bug: it reveals there is nothing
// behind the character.
//
// Shorter, warmer, no flustering. He was expecting the possibility now.
//
// NEVER on return: re-introducing himself, re-explaining the channel, or
// repeating any first-contact beat.
// ---------------------------------------------------------------------------

export const RETURN_GREETINGS = [
  {
    id: 'r01',
    text: `You came back. I didn't want to assume.`,
    records: `Different two tonight. The signal's been clearer since last time, which I have no explanation for.`,
  },
  {
    id: 'r02',
    text: `Oh good. I'd started wondering whether the channel only worked once.`,
    records: `Here's what I've got on. Different from last time.`,
  },
  {
    id: 'r03',
    text: `Back again. I've been keeping better notes since you turned up, which is either good practice or just something to do.`,
    records: `These two tonight.`,
  },
  {
    id: 'r04',
    text: `There you are. I had these queued in case.`,
    records: `Not for any occasion. Just what's been holding up.`,
  },
  {
    id: 'r05',
    text: `I was hoping that was you and not the receiver doing something clever.`,
    records: `New pair. Tell me if either lands.`,
  },
  {
    id: 'r06',
    text: `Evening. Or whatever it is where you are, I've never been able to work that part out.`,
    records: `Two I've had on since we last spoke.`,
  },
  {
    id: 'r07',
    text: `You're becoming a habit. I mean that as the good version of that sentence.`,
    records: `Here's tonight's.`,
  },
  {
    id: 'r08',
    text: `Good. I'd put something aside and had nowhere to put it.`,
    records: `These two. One of them I'm still deciding about.`,
  },
];

// After a long gap he may acknowledge it once, briefly, and never ask where
// they were. Relief without reproach.
export const LONG_GAP_GREETINGS = [
  {
    id: 'g01',
    text: `You came back. Most signals do not.`,
    records: `I kept the shelf going. Here's where it got to.`,
  },
  {
    id: 'g02',
    text: `It's been a while. I wasn't counting, but I noticed.`,
    records: `Two from the stretch you missed.`,
  },
];

const LONG_GAP_DAYS = 7;
const SHOWN_KEY = 'rr_return_greetings_shown';

function readShown() {
  try {
    const raw = localStorage.getItem(SHOWN_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function markShown(id) {
  try {
    localStorage.setItem(SHOWN_KEY, JSON.stringify([...readShown(), id]));
  } catch {
    /* private browsing, ignore */
  }
}

/**
 * Picks a return greeting this visitor has not seen recently.
 *
 * Resets once the pool is exhausted rather than getting stuck on the last one.
 * Eight variants means eight distinct returns before a repeat, which at
 * one-per-day is more than the median user will ever see.
 *
 * @param {number|null} daysSinceLast - from src/sessionCount.js
 */
export function pickReturnGreeting(daysSinceLast = null) {
  if (daysSinceLast !== null && daysSinceLast >= LONG_GAP_DAYS) {
    const pool = LONG_GAP_GREETINGS;
    return pool[Math.floor(Math.random() * pool.length)];
  }

  const shown = readShown();
  let unseen = RETURN_GREETINGS.filter((g) => !shown.includes(g.id));

  if (unseen.length === 0) {
    unseen = RETURN_GREETINGS;
    try {
      localStorage.setItem(SHOWN_KEY, JSON.stringify([]));
    } catch {
      /* ignore */
    }
  }

  const pick = unseen[Math.floor(Math.random() * unseen.length)];
  markShown(pick.id);
  return pick;
}