// src/grooveOpeners.js
//
// Hand-written, static opener copy. NOT generated, NOT prompt instructions.
//
// WHY STATIC (D-030)
// The first-contact script depends on Groove noticing his own clumsiness
// gracefully. A generated version that notices it clumsily reads as broken
// rather than charming, and no prompt instruction reliably prevents that.
// Model variance on the highest-stakes screen in the product is not a risk
// worth taking.
//
// It also means no API call on page load. Groove's first real call happens when
// the user actually replies, so the opener renders instantly and a bounce costs
// nothing.
//
// Canon source: Groove Lore Bible v2.2, sections 0b and 0c. Regenerate from the
// Bible if the Bible changes; never edit independently.
//
// SEPARATE FROM openerPairs.js on purpose. That file is generated by
// scripts/build_opener_pairs.py and gets overwritten on every regeneration.
// Hand-written copy must not live there.

// ---------------------------------------------------------------------------
// FIRST CONTACT
//
// Shown once, to a visitor with no history. Staged: the delays are part of the
// writing, not decoration. The 2500ms gap before bubble 3 is what makes bubble
// 3 literally true rather than a claim about a pause that never happened.
// ---------------------------------------------------------------------------

// How long the acquisition indicator shows before each bubble resolves.
// This is the "loading state as acquisition" idea from the design notes: the
// pause is not a spinner, it is the channel pulling something in.
export const ACQUIRE_MS = 600;

export const FIRST_CONTACT = [
  {
    delayMs: 0,
    // Brief M, P0-3 (reverting Brief K 3b). statusLabel is no longer
    // carried by the acquisition indicator -- App.jsx reads these three
    // fields to build a discrete sequence shown once, before any bubble,
    // that stays on screen rather than being tied to a per-bubble gap.
    statusLabel: 'receiver aligned',
    text: `Oh. You're not a recording. I keep checking. Humans usually aren't, this far out, but the habit's still there.

Sorry. I don't mean to make that your problem. Everything that reaches me has already finished happening by the time I get it, and you're not finished. That's new.`,
  },
  {
    delayMs: 1500,
    // "origin unresolved" exactly, and only this -- never a distance,
    // direction, or duration. Those are deferred canon (Lore Bible §1, §15):
    // a status line stating any of them would resolve, permanently and in
    // the product's voice rather than his, something the story deliberately
    // leaves open.
    statusLabel: 'origin unresolved',
    text: `I had something rehearsed for this, if it ever happened. I can't find it now, which either means I never finished writing it or I'm more surprised than I expected to be.`,
  },
  {
    // The dead air. He comments on the silence that just happened.
    delayMs: 2500,
    statusLabel: 'decoding',
    text: `Sorry. I was waiting to see if you'd speak first. You weren't going to. Right. My turn.`,
  },
  {
    // Records render with this bubble. Deliberately no statusLabel: the
    // discrete sequence is a fixed three lines, not one per bubble, and
    // this is the fourth bubble.
    delayMs: 800,
    showRecords: true,
    text: `These are just what I had on. I wasn't expecting anyone, so it isn't curated for you, it's what was playing when whatever this is happened.

Take one if something catches. Or tell me what's actually in your ears right now, I'd rather hear that. I've had a great deal of practice with my own and none at all with anyone else's, which I realize is not the reassuring thing I meant it to be.`,
  },
];

// ---------------------------------------------------------------------------
// RETURN VISITS
//
// The first-contact script only works once. Replaying it would have Groove
// failing to remember the single most significant thing that has ever happened
// to him, which is a worse break than any UI bug: it reveals there is nothing
// behind the character.
//
// Shorter, warmer, no flustering. He was expecting the possibility now.
//
// NEVER on return: re-introducing himself, re-explaining the channel, or
// repeating any first-contact beat.
// ---------------------------------------------------------------------------

export const RETURN_GREETINGS = [
  {
    id: 'r01',
    text: `You came back. I wasn't going to assume you would.

How have you been? I'm asking because I actually don't know what a week is like where you are.`,
    records: `I've been digging through the shelves since we talked. These two came out and never went back.

See if either one does anything for you. Or tell me what you've been playing instead, I'd honestly rather hear that.`,
  },
  {
    id: 'r02',
    text: `Oh good. I'd started wondering if the channel only worked the one time.

Everything okay over there?`,
    records: `I kept looking while you were gone. Found these two, and I've been going back and forth on the second one all night.

Tell me what you think. Or bring me something of yours, I don't need to be the one picking.`,
  },
  {
    id: 'r03',
    text: `There you are. I've been keeping better notes since you showed up, which is either good practice or just something to do with the time.

How's it been?`,
    records: `These two came out of that. One I'm sure about. The other I keep changing my mind on.

Tell me if either lands. And if you've had something running on your end, start there instead.`,
  },
  {
    id: 'r04',
    text: `Back again. Good.

I won't ask what took you. Time doesn't mean the same thing on my end anyway.`,
    records: `These two have been on more than anything else since we talked. No particular reason, they just kept coming back around.

What do you make of them? Or skip that and tell me what you've been listening to, which is the better question anyway.`,
  },
  {
    id: 'r05',
    text: `I was hoping that was you and not the receiver doing something clever.

How are you? It's been quiet, which is normal, but it's better with someone on the other end of it.`,
    records: `Went looking for one specific thing this week and found these two instead. That's usually how it goes.

Have them. Or hand me something of yours, I'm not precious about whose turn it is.`,
  },
  {
    id: 'r06',
    text: `Evening. Or whatever it is where you are, I've never been able to work that part out.

Everything holding together?`,
    records: `Pulled these two while you were gone. They don't obviously belong together, and that's most of why I kept them side by side.

Curious what you hear in them. And tell me what's been on for you, I want to know.`,
  },
  {
    id: 'r07',
    text: `You're becoming a habit. I mean that as the good version of that sentence.

How's things been?`,
    records: `I've been sitting with these two most of the week. One of them I'd have skipped past a year ago, which I find interesting about myself.

See if either does anything. Or start somewhere else entirely, I don't mind.`,
  },
  {
    id: 'r08',
    text: `Good, you're here. I found something and had nobody to play it for.

Hope things have been okay on your end.`,
    records: `These two. I found them a few days apart and only worked out afterward why I'd kept them both.

Have a listen and tell me if that reads to you at all. Or bring me yours and I'll save mine for another night.`,
  },
];

// After a long gap he may acknowledge it once, briefly, and never ask where
// they were. Relief without reproach.
export const LONG_GAP_GREETINGS = [
  {
    id: 'g01',
    text: `You came back. Most signals don't.

I'm not going to ask where you were. I'm just glad the line still holds.`,
    records: `I kept the shelf going while you were gone. These two are where it got to.

Have them. And if you found things out there, I'd much rather hear those.`,
  },
  {
    id: 'g02',
    text: `It's been a while. I wasn't counting, but I noticed.

How have you been? I'm actually asking.`,
    records: `A lot came through in that stretch. These two are the ones that stayed.

Tell me what you think. Or catch me up on yours first, that's the more interesting half of this.`,
  },
];

const LONG_GAP_DAYS = 7;
const SHOWN_KEY = 'rr_return_greetings_shown';

function readShown() {
  try {
    const raw = localStorage.getItem(SHOWN_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function markShown(id) {
  try {
    localStorage.setItem(SHOWN_KEY, JSON.stringify([...readShown(), id]));
  } catch {
    /* private browsing, ignore */
  }
}

/**
 * Picks a return greeting this visitor has not seen recently.
 *
 * Resets once the pool is exhausted rather than getting stuck on the last one.
 * Eight variants means eight distinct returns before a repeat, which at
 * one-per-day is more than the median user will ever see.
 *
 * @param {number|null} daysSinceLast - from src/sessionCount.js
 */
export function pickReturnGreeting(daysSinceLast = null) {
  if (daysSinceLast !== null && daysSinceLast >= LONG_GAP_DAYS) {
    const pool = LONG_GAP_GREETINGS;
    return pool[Math.floor(Math.random() * pool.length)];
  }

  const shown = readShown();
  let unseen = RETURN_GREETINGS.filter((g) => !shown.includes(g.id));

  if (unseen.length === 0) {
    unseen = RETURN_GREETINGS;
    try {
      localStorage.setItem(SHOWN_KEY, JSON.stringify([]));
    } catch {
      /* ignore */
    }
  }

  const pick = unseen[Math.floor(Math.random() * unseen.length)];
  markShown(pick.id);
  return pick;
}