// src/grooveOpeners.js
//
// Hand-written, static opener copy. NOT generated, NOT prompt instructions.
//
// WHY STATIC (D-030)
// The first-contact script depends on Groove noticing his own clumsiness
// gracefully. A generated version that notices it clumsily reads as broken
// rather than charming, and no prompt instruction reliably prevents that.
// Model variance on the highest-stakes screen in the product is not a risk
// worth taking.
//
// It also means no API call on page load. Groove's first real call happens when
// the user actually replies, so the opener renders instantly and a bounce costs
// nothing.
//
// Canon source: Groove Lore Bible v2.2, sections 0b and 0c. Regenerate from the
// Bible if the Bible changes; never edit independently.
//
// SEPARATE FROM openerPairs.js on purpose. That file is generated by
// scripts/build_opener_pairs.py and gets overwritten on every regeneration.
// Hand-written copy must not live there.

// ---------------------------------------------------------------------------
// FIRST CONTACT
//
// Shown once, to a visitor with no history. Staged: the delays are part of the
// writing, not decoration. The 2500ms gap before bubble 3 is what makes bubble
// 3 literally true rather than a claim about a pause that never happened.
// ---------------------------------------------------------------------------

// How long the acquisition indicator shows before each bubble resolves.
// This is the "loading state as acquisition" idea from the design notes: the
// pause is not a spinner, it is the channel pulling something in.
export const ACQUIRE_MS = 600;

export const FIRST_CONTACT = [
  {
    delayMs: 0,
    text: `Oh. You're not a recording. I keep checking. Humans usually aren't, this far out, but the habit's still there.

Sorry. I don't mean to make that your problem. Everything that reaches me has already finished happening by the time I get it, and you're not finished. That's new.`,
  },
  {
    delayMs: 1500,
    text: `I had something rehearsed for this, if it ever happened. I can't find it now, which either means I never finished writing it or I'm more surprised than I expected to be.`,
  },
  {
    // The dead air. He comments on the silence that just happened.
    delayMs: 2500,
    text: `Sorry. I was waiting to see if you'd speak first. You weren't going to. Right. My turn.`,
  },
  {
    // Records render with this bubble.
    delayMs: 800,
    showRecords: true,
    text: `These are just what I had on. I wasn't expecting anyone, so it isn't curated for you, it's what was playing when whatever this is happened.

Take one if something catches. Or tell me what's actually in your ears right now, I'd rather hear that. I've had a great deal of practice with my own and none at all with anyone else's, which I realize is not the reassuring thing I meant it to be.`,
  },
];

// ---------------------------------------------------------------------------
// RETURN VISITS
//
// The first-contact script only works once. Replaying it would have Groove
// failing to remember the single most significant thing that has ever happened
// to him, which is a worse break than any UI bug: it reveals there is nothing
// behind the character.
//
// Shorter, warmer, no flustering. He was expecting the possibility now.
//
// NEVER on return: re-introducing himself, re-explaining the channel, or
// repeating any first-contact beat.
// ---------------------------------------------------------------------------

export const RETURN_GREETINGS = [
  {
    id: 'r01',
    text: `You came back. I didn't want to assume, so I'd left it alone.

How have you been? Not asking for form's sake, I have genuinely no idea what a week is like where you are.`,
    records: `I've been going through the shelves since we spoke. Pulled these two out and haven't put them back yet.

Have a listen if you want. Or ignore them entirely and tell me what you've actually been playing, I'd take that over my own picks most nights.`,
  },
  {
    id: 'r02',
    text: `Oh good. I'd started wondering whether the channel only worked the once.

Everything alright over there?`,
    records: `I kept digging while you were gone. These two came out of it and I've been going back and forth on the second one all evening.

See what you think. Or bring me something instead, I don't need to be the one choosing.`,
  },
  {
    id: 'r03',
    text: `There you are. I've been keeping better notes since you turned up, which is either good practice or just something to do with the time.

How's it been?`,
    records: `Found these two somewhere in the middle of that. One of them I'm fairly sure about, the other I keep changing my mind on.

Tell me if either lands. And if you've got something of your own going, I'd rather hear about that first.`,
  },
  {
    id: 'r04',
    text: `Back again. Good.

I won't ask what took you, time doesn't mean the same thing on my end anyway.`,
    records: `I've had these two on more than anything else since we last spoke. Not for any occasion, they just kept coming back around.

What do you make of them? Or skip that and tell me what you've been listening to, which is the more interesting question.`,
  },
  {
    id: 'r05',
    text: `I was hoping that was you and not the receiver doing something clever.

How are you? I've had a quiet stretch, which is normal, but it's better with someone on the other end of it.`,
    records: `Went looking for something specific this week and found these two instead, which is usually how it goes.

Take a listen. Or hand me something of yours, I'm not precious about whose turn it is.`,
  },
  {
    id: 'r06',
    text: `Evening. Or whatever it is where you are, I've never been able to work that part out.

Everything holding together?`,
    records: `I pulled these while you were away. They don't obviously belong together and that's most of why I kept them side by side.

Curious what you hear in them. And tell me what's been on for you, I'd like to know.`,
  },
  {
    id: 'r07',
    text: `You're becoming a habit. I mean that as the good version of that sentence.

How's things?`,
    records: `Been sitting with these two most of the week. One of them I'd have skipped past a year ago, which I find interesting about myself.

See if either does anything for you. Or start somewhere else entirely, I don't mind.`,
  },
  {
    id: 'r08',
    text: `Good, you're here. I'd put something aside and had nowhere to put it.

Hope it's been alright on your end.`,
    records: `These two. I found them a few days apart and only realised afterwards why I'd kept them both.

Have a listen and tell me if that reads to you at all. Or bring me yours and I'll leave mine for another night.`,
  },
];

// After a long gap he may acknowledge it once, briefly, and never ask where
// they were. Relief without reproach.
export const LONG_GAP_GREETINGS = [
  {
    id: 'g01',
    text: `You came back. Most signals do not.

I'm not going to ask where you were. Just glad the line still holds.`,
    records: `I kept the shelf going in the meantime. These two are where it got to.

Have a listen. And if you've found things while you were gone, I'd much rather hear those.`,
  },
  {
    id: 'g02',
    text: `It's been a while. I wasn't counting, but I noticed.

How have you been? Genuinely asking.`,
    records: `A lot came through in that stretch. These two are the ones that stayed.

See what you think. Or catch me up on yours first, that's the more interesting half of this.`,
  },
];

const LONG_GAP_DAYS = 7;
const SHOWN_KEY = 'rr_return_greetings_shown';

function readShown() {
  try {
    const raw = localStorage.getItem(SHOWN_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function markShown(id) {
  try {
    localStorage.setItem(SHOWN_KEY, JSON.stringify([...readShown(), id]));
  } catch {
    /* private browsing, ignore */
  }
}

/**
 * Picks a return greeting this visitor has not seen recently.
 *
 * Resets once the pool is exhausted rather than getting stuck on the last one.
 * Eight variants means eight distinct returns before a repeat, which at
 * one-per-day is more than the median user will ever see.
 *
 * @param {number|null} daysSinceLast - from src/sessionCount.js
 */
export function pickReturnGreeting(daysSinceLast = null) {
  if (daysSinceLast !== null && daysSinceLast >= LONG_GAP_DAYS) {
    const pool = LONG_GAP_GREETINGS;
    return pool[Math.floor(Math.random() * pool.length)];
  }

  const shown = readShown();
  let unseen = RETURN_GREETINGS.filter((g) => !shown.includes(g.id));

  if (unseen.length === 0) {
    unseen = RETURN_GREETINGS;
    try {
      localStorage.setItem(SHOWN_KEY, JSON.stringify([]));
    } catch {
      /* ignore */
    }
  }

  const pick = unseen[Math.floor(Math.random() * unseen.length)];
  markShown(pick.id);
  return pick;
}